version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FLASK_ENV=${FLASK_ENV}
    volumes:
      - .:/home/hbnb/app
      - hbnb_data:/home/hbnb/hbnb_data
    depends_on:
      - db
    secrets:
      - jwt_secret

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

secrets:
  jwt_secret:
    file: ./jwt_secret.txt

volumes:
  postgres_data:
  hbnb_data:
